// Builds a throwaway vault for stress-testing the app: hundreds of pages, one page with thousands of
// nodes and edges, and notes with very long markdown bodies.
// Usage: pnpm dlx tsx packages/vault-core/scripts/seed-stress.ts "<new vault folder>" "<existing vault folder for node-types.json>"

import { promises as fs } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { edge, node, writeCanvas } from './seed-lib';
import type { StoredEdge, StoredNode } from '../src/index';

const [vaultPath, typesFrom] = process.argv.slice(2);
if (!vaultPath || !typesFrom) throw new Error('Usage: seed-stress.ts <new vault folder> <existing vault folder>');

const PAGE_COUNT = 300;
const BIG_COLS = 50;
const BIG_ROWS = 40;
const EXTRA_EDGES = 500;
const LONG_NOTE_SIZES = [100_000, 1_000_000, 5_000_000];

// Deterministic so runs are comparable.
let seed = 42;
const rand = () => ((seed = (seed * 1103515245 + 12345) % 2 ** 31) / 2 ** 31);
const pick = <T>(xs: T[]) => xs[Math.floor(rand() * xs.length)];

const WORDS = 'graph node edge vault canvas research signal entity source claim evidence timeline note link map cluster pattern'.split(' ');
const sentence = (n: number) => Array.from({ length: n }, () => pick(WORDS)).join(' ');

function longMarkdown(bytes: number): string {
  const parts: string[] = [];
  let size = 0;
  for (let i = 1; size < bytes; i++) {
    const block =
      i % 10 === 1
        ? `## Section ${i}\n\n`
        : i % 10 === 4
          ? `- ${sentence(6)}\n- ${sentence(8)}\n- [[Page 001]] and **${pick(WORDS)}**\n\n`
          : i % 10 === 7
            ? '```ts\nconst x = items.filter((i) => i.ok).map((i) => i.id);\n```\n\n'
            : `${sentence(40)}. ${sentence(25)} \`${pick(WORDS)}\` _${pick(WORDS)}_.\n\n`;
    parts.push(block);
    size += block.length;
  }
  return `# Long note (${(bytes / 1000).toLocaleString()} KB)\n\n${parts.join('')}`;
}

const look = { color: '#5b8def', width: 2 } as const;

async function main() {
  await fs.mkdir(`${vaultPath}/canvases`, { recursive: true });
  await fs.mkdir(`${vaultPath}/.mosaicflow`, { recursive: true });
  await fs.copyFile(`${typesFrom}/.mosaicflow/node-types.json`, `${vaultPath}/.mosaicflow/node-types.json`);
  const now = new Date().toISOString();
  await fs.writeFile(
    `${vaultPath}/vault.json`,
    JSON.stringify({ id: randomUUID(), name: 'StressVault', description: 'Generated by seed-stress.ts', created_at: now, updated_at: now, version: '2.0.0' }, null, 2)
  );

  // One big page: a grid of notes with neighbour edges plus random long-range ones.
  const big: StoredNode[] = [];
  const bigEdges: StoredEdge[] = [];
  const id = (r: number, c: number) => `n-${r}-${c}`;
  for (let r = 0; r < BIG_ROWS; r++) {
    for (let c = 0; c < BIG_COLS; c++) {
      big.push(node(id(r, c), 'note', [c * 320, r * 220, 260, 160], { title: `Note ${r}-${c}`, content: `**${sentence(3)}**\n\n${sentence(20)}` }));
      if (c > 0 && rand() < 0.5) bigEdges.push(edge(`e-${r}-${c}-h`, id(r, c - 1), id(r, c), '', 'right-source', 'left-target', look));
      if (r > 0 && rand() < 0.3) bigEdges.push(edge(`e-${r}-${c}-v`, id(r - 1, c), id(r, c), '', 'bottom-source', 'top-target', look));
    }
  }
  for (let i = 0; i < EXTRA_EDGES; i++) {
    const a = id(Math.floor(rand() * BIG_ROWS), Math.floor(rand() * BIG_COLS));
    const b = id(Math.floor(rand() * BIG_ROWS), Math.floor(rand() * BIG_COLS));
    if (a !== b) bigEdges.push(edge(`x-${i}`, a, b, i % 10 === 0 ? 'related' : '', 'right-source', 'left-target', look));
  }
  await writeCanvas(vaultPath, { name: `Stress - ${big.length} nodes`, description: 'Many nodes and edges on one page', tags: ['stress'] }, big, bigEdges);

  // Very long note bodies, side by side with a short one for comparison.
  const longNodes = LONG_NOTE_SIZES.map((bytes, i) =>
    node(`long-${bytes}`, 'note', [i * 460, 0, 420, 520], { title: `Long note ${(bytes / 1000).toLocaleString()} KB`, content: longMarkdown(bytes) })
  );
  longNodes.push(node('short', 'note', [LONG_NOTE_SIZES.length * 460, 0, 300, 200], { title: 'Short note', content: 'A short note for comparison.' }));
  await writeCanvas(vaultPath, { name: 'Stress - Long notes', description: '100 KB, 1 MB and 5 MB note bodies', tags: ['stress'] }, longNodes, []);

  // Many small pages.
  for (let p = 1; p <= PAGE_COUNT; p++) {
    const name = `Page ${String(p).padStart(3, '0')}`;
    const nodes = Array.from({ length: 5 }, (_, i) =>
      node(`p${p}-n${i}`, 'note', [i * 300, 0, 260, 160], { title: `${name} · ${i + 1}`, content: `${sentence(15)}. See [[Page ${String(((p % PAGE_COUNT) + 1)).padStart(3, '0')}]].` })
    );
    const edges = nodes.slice(1).map((n, i) => edge(`p${p}-e${i}`, nodes[i].id, n.id, '', 'right-source', 'left-target', look));
    await writeCanvas(vaultPath, { name, description: `Small page ${p} of ${PAGE_COUNT}`, tags: ['stress', `bucket-${p % 10}`] }, nodes, edges);
  }
}

await main();
